import { writeFileSync } from 'fs'
import { join } from 'path'

// Export data as JSON that can be imported manually through Sanity Studio
const seedData = {
  hero: {
    _type: 'hero',
    badge: 'Trusted Since 1997',
    title: 'Industrial',
    titleHighlight: 'Machine Tools',
    titleSuffix: 'Excellence',
    description: "India's premier supplier of premium used machine tools. Specializing in cylindrical grinding, boring machines, and precision manufacturing equipment for industrial excellence.",
    features: [
      'Premium Quality Machines',
      'Expert Technical Support',
      'Competitive Pricing',
      'Nationwide Delivery',
    ],
    primaryButtonText: 'Explore Machines',
    primaryButtonLink: '/products',
    secondaryButtonText: 'Watch Demo',
    secondaryButtonLink: '#',
    stats: [
      { label: 'Years of Excellence', value: '25+' },
      { label: 'Machines Supplied', value: '1000+' },
      { label: 'Happy Clients', value: '500+' },
    ],
  },
  products: [
    {
      _type: 'product',
      title: 'Cylindrical Grinding Machines',
      slug: { _type: 'slug', current: 'cylindrical-grinding-machines' },
      description: 'High-precision cylindrical grinding machines for external and internal grinding operations with exceptional surface finish.',
      category: 'grinding',
      specifications: 'Max Grinding Length: 1000mm, Max Swing: 400mm',
      features: ['Precision Grinding', 'CNC Control', 'Heavy Duty'],
      isInStock: true,
      dateAdded: '2024-01-15',
    },
    {
      _type: 'product',
      title: 'Horizontal Boring Machines',
      slug: { _type: 'slug', current: 'horizontal-boring-machines' },
      description: 'Heavy-duty horizontal boring machines for large-scale manufacturing operations with exceptional accuracy and reliability.',
      category: 'boring',
      specifications: 'Max Boring Diameter: 200mm, Table Size: 2000x1500mm',
      features: ['Large Capacity', 'High Precision', 'Heavy Duty'],
      isInStock: true,
      dateAdded: '2024-01-10',
    },
    {
      _type: 'product',
      title: 'Automatic Production Bore Grinding',
      slug: { _type: 'slug', current: 'automatic-production-bore-grinding' },
      description: 'Fully automated bore grinding machines for high-volume production with consistent quality and efficiency.',
      category: 'grinding',
      specifications: 'Production Rate: 200 pieces/hour, Accuracy: ±0.005mm',
      features: ['Automated', 'High Volume', 'Consistent Quality'],
      isInStock: true,
      dateAdded: '2024-01-05',
    },
    {
      _type: 'product',
      title: 'Precision Lathe Machines',
      slug: { _type: 'slug', current: 'precision-lathe-machines' },
      description: 'Advanced precision lathe machines for complex turning operations with superior accuracy and surface finish.',
      category: 'lathe',
      specifications: 'Max Turning Length: 1500mm, Max Swing: 500mm',
      features: ['High Precision', 'CNC Control', 'Versatile'],
      isInStock: true,
      dateAdded: '2023-12-20',
    },
    {
      _type: 'product',
      title: 'Gear Grinding Machines',
      slug: { _type: 'slug', current: 'gear-grinding-machines' },
      description: 'Specialized gear grinding machines for precision gear manufacturing with exceptional accuracy and surface quality.',
      category: 'gear',
      specifications: 'Max Gear Diameter: 800mm, Module Range: 1-20',
      features: ['Gear Grinding', 'High Accuracy', 'Precision'],
      isInStock: true,
      dateAdded: '2023-12-15',
    },
    {
      _type: 'product',
      title: 'CNC Machining Centers',
      slug: { _type: 'slug', current: 'cnc-machining-centers' },
      description: 'Advanced CNC machining centers for complex manufacturing operations with automation and precision control.',
      category: 'cnc',
      specifications: 'Work Envelope: 1000x800x600mm, Spindle Speed: 8000 RPM',
      features: ['CNC Control', 'Automation', 'High Productivity'],
      isInStock: true,
      dateAdded: '2023-12-10',
    },
  ],
  about: {
    _type: 'about',
    title: 'About',
    titleHighlight: 'Shivam Enterprise',
    description: 'Since 1997, we have been India\'s trusted supplier of premium used machine tools. Our commitment to quality, reliability, and customer satisfaction has made us a leading name in the industrial machinery sector.',
    stats: [
      {
        icon: 'Award',
        title: '25+ Years Experience',
        description: 'Decades of expertise in machine tool industry',
        value: '25+',
        color: 'from-brand-orange to-accent-600',
      },
      {
        icon: 'Users',
        title: '500+ Happy Clients',
        description: 'Satisfied customers across India',
        value: '500+',
        color: 'from-brand-darkBlue to-primary-800',
      },
      {
        icon: 'Clock',
        title: '24/7 Support',
        description: 'Round-the-clock customer service',
        value: '24/7',
        color: 'from-brand-gray to-gray-600',
      },
      {
        icon: 'Shield',
        title: 'Quality Assured',
        description: 'All machines thoroughly tested',
        value: '100%',
        color: 'from-green-500 to-green-600',
      },
    ],
    features: [
      {
        title: 'Premium Quality',
        description: 'All our used machine tools are carefully inspected and refurbished to ensure optimal performance and reliability.',
      },
      {
        title: 'Expert Service',
        description: 'Our experienced team provides comprehensive support from selection to installation and maintenance.',
      },
      {
        title: 'Wide Inventory',
        description: 'Extensive range of machine tools including grinding, boring, lathe, and CNC machines from top manufacturers.',
      },
      {
        title: 'Competitive Pricing',
        description: 'Best value for money with competitive pricing on premium used machine tools without compromising quality.',
      },
    ],
  },
  footer: {
    _type: 'footer',
    companyName: 'Shivam Enterprise',
    description: 'Leading supplier of premium used machine tools since 1997. We deliver precision, reliability, and innovation to industries across India with our extensive inventory and expert service.',
    phone: '+91-9824080055',
    email: 'shivamenterprise@yahoo.com',
    address: '6- Ganpat Colony, Opp, Civil Hospital, Shahibaug, Ahmedabad, Gujarat - 380016',
    companyLinks: [
      { name: 'About Us', href: '/about' },
      { name: 'Our Team', href: '/team' },
      { name: 'Careers', href: '/careers' },
      { name: 'News', href: '/news' },
    ],
    productLinks: [
      { name: 'Boring Machines', href: '/products/boring' },
      { name: 'Lathe Machines', href: '/products/lathe' },
      { name: 'Gear Machines', href: '/products/gear' },
      { name: 'CNC Machines', href: '/products/cnc' },
    ],
    serviceLinks: [
      { name: 'Machine Installation', href: '/services/installation' },
      { name: 'Maintenance', href: '/services/maintenance' },
      { name: 'Training', href: '/services/training' },
      { name: 'Support', href: '/services/support' },
    ],
    supportLinks: [
      { name: 'Contact Us', href: '/contact' },
      { name: 'FAQ', href: '/faq' },
      { name: 'Documentation', href: '/docs' },
      { name: 'Privacy Policy', href: '/privacy' },
    ],
    socialLinks: [
      { platform: 'Facebook', url: '#' },
      { platform: 'Twitter', url: '#' },
      { platform: 'LinkedIn', url: '#' },
      { platform: 'Instagram', url: '#' },
    ],
  },
  contact: {
    _type: 'contact',
    title: 'Get In',
    titleHighlight: 'Touch',
    description: 'Ready to find the perfect machinery solution for your business? Contact our experts today for personalized assistance and quotes.',
    contactInfo: [
      {
        type: 'phone',
        title: 'Phone',
        details: ['+91-9824080055'],
        color: 'from-blue-500 to-blue-600',
      },
      {
        type: 'email',
        title: 'Email',
        details: ['shivamenterprise@yahoo.com'],
        color: 'from-green-500 to-green-600',
      },
      {
        type: 'address',
        title: 'Address',
        details: [
          '6- Ganpat Colony, Opp, Civil Hospital',
          'Shahibaug, Ahmedabad, Gujarat - 380016',
          'India',
        ],
        color: 'from-red-500 to-red-600',
      },
      {
        type: 'hours',
        title: 'Business Hours',
        details: [
          'Mon - Fri: 9:00 AM - 6:00 PM',
          'Sat: 9:00 AM - 2:00 PM',
          'Sun: Closed',
        ],
        color: 'from-purple-500 to-purple-600',
      },
    ],
    stats: [
      { value: '25+', label: 'Years Experience' },
      { value: '1000+', label: 'Machines Supplied' },
      { value: '500+', label: 'Happy Clients' },
      { value: '24/7', label: 'Support' },
    ],
  },
  machineToolCategories: [
    {
      _type: 'machineToolCategory',
      name: 'Boring Machines',
      slug: { _type: 'slug', current: 'boring-machines' },
      description: 'Horizontal and floor type boring machines for precision manufacturing',
      icon: 'Wrench',
      count: '25+ Machines',
      href: '/products?category=boring',
      color: 'from-blue-500 to-blue-600',
      order: 1,
    },
    {
      _type: 'machineToolCategory',
      name: 'Grinding Machines',
      slug: { _type: 'slug', current: 'grinding-machines' },
      description: 'Cylindrical, surface, and roll grinders for superior finish',
      icon: 'Settings',
      count: '30+ Machines',
      href: '/products?category=grinding',
      color: 'from-green-500 to-green-600',
      order: 2,
    },
    {
      _type: 'machineToolCategory',
      name: 'Lathe Machines',
      slug: { _type: 'slug', current: 'lathe-machines' },
      description: 'Vertical and horizontal lathes for turning operations',
      icon: 'Gauge',
      count: '20+ Machines',
      href: '/products?category=lathe',
      color: 'from-orange-500 to-orange-600',
      order: 3,
    },
    {
      _type: 'machineToolCategory',
      name: 'CNC Machines',
      slug: { _type: 'slug', current: 'cnc-machines' },
      description: 'CNC machining centers and turning centers',
      icon: 'Cog',
      count: '15+ Machines',
      href: '/products?category=cnc',
      color: 'from-purple-500 to-purple-600',
      order: 4,
    },
    {
      _type: 'machineToolCategory',
      name: 'Milling Machines',
      slug: { _type: 'slug', current: 'milling-machines' },
      description: 'Plano millers and vertical milling machines',
      icon: 'Drill',
      count: '18+ Machines',
      href: '/products?category=milling',
      color: 'from-red-500 to-red-600',
      order: 5,
    },
    {
      _type: 'machineToolCategory',
      name: 'Gear Machines',
      slug: { _type: 'slug', current: 'gear-machines' },
      description: 'Gear cutting and finishing machines',
      icon: 'Layers',
      count: '12+ Machines',
      href: '/products?category=gear',
      color: 'from-indigo-500 to-indigo-600',
      order: 6,
    },
    {
      _type: 'machineToolCategory',
      name: 'Drill Machines',
      slug: { _type: 'slug', current: 'drill-machines' },
      description: 'Radial drills and precision drilling equipment',
      icon: 'Drill',
      count: '10+ Machines',
      href: '/products?category=drill',
      color: 'from-cyan-500 to-cyan-600',
      order: 7,
    },
    {
      _type: 'machineToolCategory',
      name: 'Others',
      slug: { _type: 'slug', current: 'others' },
      description: 'Planning machines and specialized equipment',
      icon: 'Factory',
      count: '15+ Machines',
      href: '/products?category=others',
      color: 'from-gray-500 to-gray-600',
      order: 8,
    },
  ],
}

// Export to JSON file
const outputPath = join(process.cwd(), 'sanity-seed-data.json')
writeFileSync(outputPath, JSON.stringify(seedData, null, 2))

console.log('✅ Data exported to sanity-seed-data.json')
console.log('\n📝 You can now:')
console.log('1. Open Sanity Studio: npm run studio')
console.log('2. Manually create documents using the data in sanity-seed-data.json')
console.log('3. Or use Sanity CLI to import: sanity dataset import sanity-seed-data.json production')

