import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'product',
  title: 'Product/Machine',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'machineToolCategory' }],
      validation: (Rule) => Rule.required(),
      description: 'Select or create a category for this machine.',
    }),
    defineField({
      name : 'subcategory',
      title: 'Subcategory',
      type: 'string',
    }),
    // defineField({
    //   name: 'features',
    //   title: 'Features',
    //   type: 'array',
    //   of: [{ type: 'string' }],
    // }),
    defineField({
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [
        {
          type: 'image',
          options: {
            hotspot: true,
          },
        },
      ],
    }),
    defineField({
      name: 'isInStock',
      title: 'In Stock',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'dateAdded',
      title: 'Date Added',
      type: 'date',
      initialValue: () => new Date().toISOString().split('T')[0],
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'string',
      description: 'Price or price range',
    }),
    defineField({
      name: 'year',
      title: 'Year',
      type: 'number',
    }),
    defineField({
      name: 'condition',
      title: 'Condition',
      type: 'string',
      options: {
        list: [
          { title: 'Excellent', value: 'excellent' },
          { title: 'Very Good', value: 'very-good' },
          { title: 'Good', value: 'good' },
          { title: 'Fair', value: 'fair' },
        ],
      },
    }),
    defineField({
      name: 'technicalSpecs',
      title: 'Technical Specifications',
      type: 'object',
      fields: [
        { name: 'manufacturer', title: 'Manufacturer', type: 'string' },
        { name: 'controlSystem', title: 'Control system', type: 'string' },
        { name: 'workingSpindleDiameter', title: 'Diameter of working spindle', type: 'string' },
        { name: 'travelX', title: 'Travel X-axis', type: 'string' },
        { name: 'travelY', title: 'Travel Y-axis', type: 'string' },
        { name: 'spindleSpeed', title: 'Spindle speed', type: 'string' },
        { name: 'travelW', title: 'Spindle travel - W axis', type: 'string' },
        { name: 'coolingThroughSpindle', title: 'Cooling through spindle', type: 'string' },
        { name: 'coolingPressure', title: 'Pressure of cooling', type: 'string' },
        { name: 'toolMagazine', title: 'Tool magazine', type: 'string' },
        { name: 'spindleTaper', title: 'Spindle taper', type: 'string' },
        { name: 'travelZ', title: 'Travel Z-axis', type: 'string' },
        { name: 'axisV', title: 'Axis V', type: 'string' },
        { name: 'clampingAreaOfTable', title: 'Clamping area of table', type: 'string' },
        { name: 'maxLoadOfTable', title: 'Max. load of table', type: 'string' },
        { name: 'mainMotorPower', title: 'Main motor power', type: 'string' },
        { name: 'machineDimensions', title: 'Machine dimensions l x w x h', type: 'string' },
        { name: 'machineWeight', title: 'Machine weight', type: 'string' },
        { name: 'clampingAreaOfRotaryTable', title: 'Clamping area of rotary table', type: 'string' },
        { name: 'numberOfPositionsInMagazine', title: 'Number of positions in magazine', type: 'string' },
        { name: 'totalInput', title: 'Total input', type: 'string' },
        { name: 'facePlateDiameter', title: 'Face plate diameter', type: 'string' },
        { name: 'maxDiameterOfFaceTurning', title: 'Max. diameter of face turning', type: 'string' },
        { name: 'rapidFeed', title: 'Rapid feed', type: 'string' },
        { name: 'tableDimensions', title: 'Table dimensions', type: 'string' },
        { name: 'ramDimensions', title: 'Ram dimensions', type: 'string' },
        { name: 'ramTravelZ', title: 'Ram travel (Z)', type: 'string' },
        { name: 'maxDiameterOfMilledWheel', title: 'Max. diameter of milled wheel', type: 'string' },
        { name: 'rapidFeedX', title: 'X-axis rapid feed', type: 'string' },
        { name: 'rapidFeedY', title: 'Y-axis rapid feed', type: 'string' },
        { name: 'rapidFeedZ', title: 'Z-axis rapid feed', type: 'string' },
        { name: 'numberOfDrivenAxes', title: 'Number of driven axes', type: 'string' },
        { name: 'maxWeightOfWorkpiece', title: 'Max. weight of workpiece', type: 'string' },
        { name: 'numberOfPallets', title: 'Number of pallets', type: 'string' },
        { name: 'axisB', title: 'Axis B', type: 'string' },
        { name: 'axisC', title: 'Axis C', type: 'string' },
        { name: 'spaceOfMachine', title: 'Space of machine', type: 'string' },
        { name: 'accuracyRepeatability', title: 'Accuracy - repeatability', type: 'string' },
        { name: 'accuracyPositioning', title: 'Accuracy - positioning', type: 'string' },
        { name: 'maxDiameterOfWorkpiece', title: 'Max. diameter of workpiece', type: 'string' },
        { name: 'maxLengthOfWorkpiece', title: 'Max. length of workpiece', type: 'string' },
        { name: 'maxWorkpieceHeight', title: 'Max. workpiece height', type: 'string' },
        { name: 'drivenTools', title: 'Driven Tools', type: 'string' },
        { name: 'axisW', title: 'Axis W', type: 'string' },
        { name: 'tableRotation', title: 'Table Rotation', type: 'string' },
        { name: 'turretHead', title: 'Turret head', type: 'string' },
        { name: 'clampingDiameterOfRotaryTable', title: 'Clamping diameter of rotary table', type: 'string' },
        { name: 'maxTorqueOfSpindle', title: 'Max. torque of spindle', type: 'string' },
        { name: 'swingOverCrossSlide', title: 'Swing over cross slide', type: 'string' },
        { name: 'spindleBore', title: 'Spindle bore', type: 'string' },
        { name: 'rotationsOfClampingPlate', title: 'Rotations of clamping plate', type: 'string' },
        { name: 'feedingSpeed', title: 'Feeding speed', type: 'string' },
        { name: 'numberOfToolPositionsDriven', title: 'Number of tool positions (driven)', type: 'string' },
        { name: 'speedDrivenTools', title: 'Speed driven tools', type: 'string' },
        { name: 'turnTableDiameter', title: 'Turn table diameter', type: 'string' },
        { name: 'turningLength', title: 'Turning length', type: 'string' },
        { name: 'barLoader', title: 'Bar loader', type: 'string' },
        { name: 'slopingBed', title: 'Sloping bed', type: 'string' },
        { name: 'maxBarDiameter', title: 'Max. bar diameter', type: 'string' },
        { name: 'swingOverBed', title: 'Swing over bed', type: 'string' },
        { name: 'chuckDiameter', title: 'Chuck diameter', type: 'string' },
        { name: 'distanceBetweenCentres', title: 'Distance between centres', type: 'string' },
        { name: 'millingHead', title: 'Milling head', type: 'string' },
        { name: 'counterspindle', title: 'Counterspindle', type: 'string' },
        { name: 'travelYLathe', title: 'Travel Y-axis (lathe)', type: 'string' },
        { name: 'maxDrillingDiameter', title: 'Max. drilling diameter', type: 'string' },
        { name: 'grindingSpindleSpeed', title: 'Grinding spindle speed', type: 'string' },
      ],
      options: {
        collapsible: true,
        collapsed: true,
      }
    }),
  ],
  preview: {
    select: {
      title: 'title',
      category: 'category',
      media: 'images.0',
    },
    prepare({ title, category, media }) {
      return {
        title,
        subtitle: category ? `Category Document` : 'No Category',
        media,
      }
    },
  },
})

